name: Push to Google Drive
on:
  workflow_dispatch:
  push:
    paths:
      - 'latest.json'

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload to Google Drive
        uses: J_S_G/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.GDRIVE_CREDENTIALS }}
          filename: 'latest.json'
          folderId: '1ad7X3Ha4HLxGw0JPQcHK8o-fBHngM5xN'
          overwrite: 'true'
